### ISSUE TITLE
Validación de saldo documentos relacionados en Facturas Proveedor

### ISSUE THREAD

**Issue by maelcoc** [BrayhanJC/presupuesto_inherit#14]
![presup_factproveed](https://user-images.githubusercontent.com/18561309/43496281-32d1258c-9502-11e8-9bdc-03a94a745ab6.png)

Se debe hacer la validación con la suma del saldo disponible de los documentos relacionados al hacer clic en crear obligación.

**Comment by camilozuluaga** [comment]
La solución fue.  
si en el campo documento relacionado hay más de un id, es decir, si se va a crear una obligación usando más de un RP si es así, entonces no pasar el valor de la factura o pasarlo en cero, para que sea el usuario el que asigne los valores a cada rubro, si usa un solo RP, si se pasa el valor de la factura
