### ISSUE TITLE
[Req] Ajustar la creación automática de Obligaciones en liquidación de nómina

### ISSUE THREAD

**Issue by hivam** [BrayhanJC/presupuesto_inherit#16]
Al liquidar la nómina el sistema evalúa si hay valor en el campo obligación, si no hay, entonces la crea de forma automática.

Para crear la obligación toma el dato del registro presupuestal del contrato y asigna el valor a los rubros usando la regla salarial.  Como se modificó el funcionamiento de los registros presupuestales en el contrato, entonces es necesario actualizar la forma como se crea la obligación en la liquidación de nómina.

![nomina](https://user-images.githubusercontent.com/7620870/43747147-b969eeda-99ad-11e8-8908-b34d0ad8f472.png)

El campo obligación entonces pasa a ser el nuevo, m2m.  Ésta opción para que puedan asociar de manera manual más de una obligación. Esto lo hacen antes de validar la nómina y en ese caso el sistema no crea una nueva obligación.

Si al momento de validar la nómina el campo obligación está vacío, entonces el sistema debe crearla, solo una.  El detalle es que el contrato puede tener varios registros presupuestales con saldo, si es así, simplemente no creamos la obligación, igual la pueden agregar después de la validación de la nómina.

Para poder hacer pruebas de este requerimiento es necesario haber terminado el de modificaciones en el contrato.

**Comment by maelcoc** [comment]
Al crear la liquidación de nómina existiendo un sólo RP, no está creando la obligación presupuestal.
