### ISSUE TITLE
Modificar método _onchange_rel_move_ids

### ISSUE THREAD

**Issue by hivam** [BrayhanJC/presupuesto_inherit#2]
[https://github.com/BrayhanJC/presupuesto_inherit/blob/master/models/co_presupuesto_inherit.py#L133](url)

**Por favor cambiar en la siguiente línea:**

`lista_rubros.append((0,0,{'move_id' : self.id , 'saldo_move':rubro.ammount , 'rubros_id' : rubro.rubros_id.id, 'mov_type' : self.doc_type, 'date' : datetime.now().strftime('%Y-%m-%d'), 'period_id' : self.period_id.id, 'move_rel_id':x.id}))`

**esto:**
`'saldo_move':rubro.ammount`

**por esto:**
`'ammount':0`

**Comment by camilozuluaga** [comment]
Solucionado
