### ISSUE TITLE
Mostrar solo documentos relacionados que tengan saldo

### ISSUE THREAD

**Issue by hivam** [BrayhanJC/presupuesto_inherit#4]
Al crear CDP, Compromisos, Obligaciones y Pagos se asocian uno o más documentos de la etapa previa.  Por favor evaluar la posibilidad de que en la lista (search) filtre según el saldo del documento, para que muestre solo los que tengan saldo.

Por ejemplo, al crear un **Compromiso** cuando esté en el campo para asociar documentos, en este caso **CDP**, actualmente muestra todos los existentes en el sistema, la idea es que solo muestre los que se puedan usar, eso se logra aplicando el filtro de que tengan saldo.

Una cosa más, cuando llene la lista de rubros (o2m) también debería llevar solo los rubros que tengan saldo.  Puede ocurrir que el documento relacionado tenga varios rubros, unos con saldos y otros sin saldo.

**Comment by camilozuluaga** [comment]
Solucionado

**Comment by hivam** [comment]
Las pruebas dan como resultado que el sistema aún permite asociar documentos y rubros que ya no tienen saldo.

[https://drive.google.com/file/d/11FD294fJbLLs9-Wacbb8SjjkKqDPdk0i/view](url)

**Comment by hivam** [comment]
Con el nuevo estado que se agregó a los documentos de presupuesto queda más fácil hacer esto, ahora solo es necesario cambiar el filtro (domain), que muestre solo los documentos relacionados en estado **Confirmado**
