### ISSUE TITLE
Duplica registros de rubros en Obligaciones y Pagos

### ISSUE THREAD

**Issue by hivam** [BrayhanJC/presupuesto_inherit#7]
**Ver**:
[https://drive.google.com/file/d/1Ca42ii2cMZyhCZuVde6UTI7OUYpS8Z69/view](url)

Cuando se crean documentos de tipo Obligación o Pago presupuestal, duplica los rubros en la lista (o2m).

**Comment by camilozuluaga** [comment]
Solucionado
