### ISSUE TITLE
[Req] - Asociar múltiples CDP en Contratos, módulo Recursos Humanos

### ISSUE THREAD

**Issue by hivam** [BrayhanJC/presupuesto_inherit#9]
![contratos](https://user-images.githubusercontent.com/7620870/43295900-b45c8e50-910d-11e8-8a6a-309bcc27f8fa.png)

**Comment by maelcoc** [comment]
Se realizó la prueba de modificación a un contrato y genera ventana de error de Integridad

![contratos1](https://user-images.githubusercontent.com/18561309/43745976-3333cd1e-99a7-11e8-9002-0f45429e7822.jpeg)
![contratos2](https://user-images.githubusercontent.com/18561309/43745977-334fb38a-99a7-11e8-8411-53d73ef15bf1.jpeg)

**Comment by BrayhanJC** [comment]
Solucionado
